# Generated by Django 5.0 on 2024-01-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_alter_category_options_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
    ]
